server:
  port: 8082

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR


brpc:
  application-name: brpc-springboot-consumer
  registry-url: zookeeper://127.0.0.1:2181
  serialize-type: hessian
  compress-type: gzip
  group: test

